name: Release to NPM

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Building package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Caching node_modules
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Caching build files
        uses: actions/cache@v3
        id: build-cache
        with:
          path: "**/dist"
          key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          check-latest: true
          cache: 'yarn'

      - name: Install dependencies 🔧
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Check for errors 🚨
        run: yarn lint

      - name: Test package 🔧
        run: yarn test:ci

      - name: Build package 📦
        run: yarn build

  release-npm:
    needs: build
    if: ${{ github.repository_owner == 'lukemorales' }}
    name: Release to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Load node_modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Load build files
        uses: actions/cache@v3
        with:
          path: "**/dist"
          key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}

      - name: Setup Node for NPM
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          check-latest: true
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish to NPM 🚀
        id: changesets
        uses: changesets/action@v1
        with:
          version: node .github/changeset-version.js
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  release-gpr:
    needs: [build, release-npm]
    name: Release to GitHub Package Manager
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Load node_modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Load build files
        uses: actions/cache@v3
        with:
          path: "**/dist"
          key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}

      - name: Setup Node for GPR
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          check-latest: true
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'

      - name: Publish to GPR 🚀
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
